version: "3.4"

services:
  blipapi:
    container_name: blipapi
    image: blipapi
    environment:
      - PORT=5000
    ports:
      - 5000:5001
    build:
      context: .
      dockerfile: Dockerfile